kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."${REGISTRY_HOSTNAME}"]
    endpoint = ["http://${REGISTRY_HOSTNAME}"]
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
