apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-pv-claim
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 20Gi
 storageClassName: gp2 # if no storage Class define - the default storage class will be selected
