---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: db-spring
  labels:
    app: db-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-spring
  template:
    metadata:
      labels:
        app: db-spring
        version: v0.0.1
    spec:
      containers:
      - name: db_mysql
        image: yanivomc/spring-mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: "music"
---
apiVersion: v1
kind: Service
metadata:
  name: db-mysql
spec:
  ports:
  - name: tcp
    targetPort: 3306
    port: 3306
  selector:
    app: db-spring
---