apiVersion: v1
kind: Pod
metadata:
  name: app-test-1
spec:
  containers:
  - name: nginx   # FIRST Container
    image: nginx:latest
    volumeMounts:
    - mountPath: /srv/www # Mount location within a container
      name: data-volume # Volume name that we created
      readOnly: true # Read Only or not
  - name: sidecar-staticgen # SECOND Container
    image: alpine/git:latest
    env: # ENVIRONMENT Variables
    - name: GIT_REPO # KEY
      value: https://github.com/cfjedimaster/HTML-Code-Demos.git # VALUE
    command: ["git"]
    args: ["clone", "$GIT_REPO", "/data-files/"]
    volumeMounts:
    - mountPath: /data-files
      name: data-volume # Volume name that we created

# Creating Volumes to be used by the above containers
  volumes:
  - name: data-volume
    emptyDir: {} # Volume Drive