version: '3.2'
# Documented from: https://docs.confluent.io/current/ksql/docs/installation/install-ksql-with-docker.html#ksql-interactive-server-settings
services:
  ksql:
    image: confluentinc/cp-ksql-server:5.3.2
    container_name: ksql
    hostname: ksql
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
        mode: host
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka1:9094
      KSQL_LISTENERS: http://0.0.0.0:8088/
      KSQL_KSQL_SERVICE_ID: ksql_service_3_
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    extra_hosts:
      - "kafka1:18.203.115.19"
      - "kafka2:18.203.115.19"
      - "kafka3:18.203.115.19"
      - "zookeeper:18.203.115.19"

  datagen:
    image: confluentinc/ksql-examples:5.3.2
    container_name: datagen
    hostname: datagen
    command: ["sleep", "1000000"]
    extra_hosts:
      - "kafka1:18.203.115.19"
      - "kafka2:18.203.115.19"
      - "kafka3:18.203.115.19"
      - "zookeeper:18.203.115.19"    
    volumes:
      - "./datagen:/files"
